server:
  port: 9090
spring:
  application:
    name: business-starter
  resources:
    static-locations: file:${aliyun.oss.urlPrefix}
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.31.16.35:3306/db01?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  rabbitmq:
    host: 118.31.16.35
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  redis:
    host: 118.31.16.35
    port: 6379
    password: 123456

mybatis:
  type-aliases-package: com/qyl/pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  accessKeyId: abc
  accessKeySecret: abc
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    bucketName: qyl-bucket
    urlPrefix: https://qyl-bucket.oss-cn-hangzhou.aliyuncs.com/image/